### ISSUE TITLE
Add (option to enable) year and month selectors

### ISSUE THREAD

**Issue by mrfelton** [Textalk/angular-schema-form-datepicker#11]
It's hard to select dates in the past without the year selector. An option to enable them would be useful.

**Comment by Dervisevic** [comment]
#16 has been merged, it will be tested and then bower released

**Comment by orderofout** [comment]
Is there a timeframe for this being bower released?

**Comment by Dervisevic** [comment]
Haven't had a time to test it but if you pull down the master and test it with options I can go ahead and release it
