### ISSUE TITLE
Datapicker ignores htmlClass completly

### ISSUE THREAD

**Issue by orderofout** [Textalk/angular-schema-form-datepicker#13]
It seems like the functionality from the angular-schema isn't completely passed through.
The htmlClass is ignored by the datepicker form field when the html is generated. But the code for the adjacent field is created as expected.

Any advice to get this working quickly?

```javascript
{
	'type': 'section',
	'htmlClass': 'row',
	'items': [
		{'key': 'recentExam', 'format': 'mm-dd-yyyy', 'htmlClass': 'col-sm-6'},
		{'key': 'examPurpose', 'htmlClass': 'col-sm-6'}
	]
},
```

This is the resulting html: http://postimg.org/image/xprmfqz6r/

**Comment by Dervisevic** [comment]
Datepicker is separate from Angular-Schema-Form and was actually written prior to htmlClass being added to ASF, it does require the template to have functionality for it and that just hasn't been done. This should be added to the todo list, nothing i could do right now.

If you need a quick fix you can add it to your template, and a Pull request would be great. You can see how it's implemented for [checkboxes here](https://github.com/Textalk/angular-schema-form/blob/master/src/directives/decorators/bootstrap/checkbox.html), look for `form.htmlClass` and `form.fieldHtmlClass` in there.
It would need to be added to the [template for the datepicker](https://github.com/Textalk/angular-schema-form-datepicker/blob/master/src/datepicker.html).

Hope that helps!

**Comment by Dervisevic** [comment]
Actually, i do have time right now, let me whip it up

**Comment by orderofout** [comment]
You are awesome! Thank you!

**Comment by Dervisevic** [comment]
Try out the 0.3.0 version and let me know if it works.

**Comment by orderofout** [comment]
Works for me. 
Thanks again!
