### ISSUE TITLE
cursor / Mousepointer wrong.

### ISSUE THREAD

**Issue by jackwinters** [Textalk/angular-schema-form-datepicker#14]
If you look at the kitchen sink example within http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html and hover the mouse pointer over the angular-schema-form-datepicker field the no-drop cursor is shown.

**Comment by Dervisevic** [comment]
Something is causing it to get a readonly attribute on the input, not sure what that is, can't see it in the schema/form or even the template for the datepicker, will investigate more when i get the time.

**Comment by Knuckles9090** [comment]
Yeah, noticed the same problem

**Comment by Knuckles9090** [comment]
It seems to be a problem with pickdate, the best course of action is to add the following css.

https://github.com/amsul/pickadate.js/issues/474

.picker__input[readonly],
.picker__input:hover {
    background: #fff;
    cursor: text;
}

**Comment by engelfrost** [comment]
I guess this is something to report upstream if it is to be fixed properly
