### ISSUE TITLE
Random default language

### ISSUE THREAD

**Issue by jackwinters** [Textalk/angular-schema-form-datepicker#15]
This may be by intent or my own ignorance about how to set the language - but the default language seems to vary unpredictably. In the kitchen sink demo it is Dutch even though the rest of the demo is English and the default for bootstrap-datepicker is en. Running on my server it is in German which is doubly odd.

**Comment by davidlgj** [comment]
There is no inherit language in schema form, it's up to the language you use in the schema and form definition. The datepicker on the other uses pickadate and it has excellent translation support, see its docs for usage (but basically you include the translation you want): http://amsul.ca/pickadate.js/date/#translations

The dutch in the demo is there for historical reasons :) I changed it when we where debugging a problem.
