### ISSUE TITLE
[Feature Request] Field Addons / Inline Forms

### ISSUE THREAD

**Issue by quietlyconfident** [Textalk/angular-schema-form-datepicker#17]
We'd like to be able to add icons / glyphs / etc. in input-group-addons to the forms as described here:
[ASF Issue 273](https://github.com/Textalk/angular-schema-form/issues/273).

If we implemented this for -datepicker and submitted a pull request, would the maintainers be amenable to merging it?  The goal is to be able to attach an icon to the field like so:

![screen shot 2015-02-27 at 3 57 30 pm](https://cloud.githubusercontent.com/assets/249930/6421265/0827e136-be9b-11e4-84a2-e06c64270cdc.png)

**Comment by Dervisevic** [comment]
I don't see why not.

**Comment by quietlyconfident** [comment]
Uploaded #18

**Comment by Dervisevic** [comment]
#18 has been merged

**Comment by quietlyconfident** [comment]
Thank you sir.  Any thoughts on when the next release might occur, so that bower users could get this patch?

**Comment by Dervisevic** [comment]
Not sure when, we have a lot of stuff going on at work. We'll get to it asap.
