### ISSUE TITLE
Date Range in Filter

### ISSUE THREAD

**Issue by ragsnas** [Textalk/angular-schema-form-datepicker#19]
Hi,

as you know, the datepicker is also used as a filter in the list view of angular-schema-form.
Problem here: Barely anyone ever wants to filter for one special date.
The most common use-case is filter for a date range (i.e. I want to see all Users who logged in during the last week).

Is there already support for this?
If not, what would be best practise to build it?

**Comment by davidlgj** [comment]
Hi @ragsnas, what do you mean by "filter in the list view of angular-schema-form"?
Are you're asking for a date widget that support choosing a range of dates?

**Comment by ragsnas** [comment]
Oui!
That is exactly what i am talking about.

**Comment by davidlgj** [comment]
The datepicker uses http://amsul.ca/pickadate.js/date/ and as far as I can tell that doesn't support ranges. 

So there are two options, either you can use two date fields to do the range or try to find another datepicker that does support ranges and make an add-on for it.
