### ISSUE TITLE
Date Picker won't show up in FormController

### ISSUE THREAD

**Issue by benoror** [Textalk/angular-schema-form-datepicker#20]
I need to now when a field is dirty ($dirty, $pristine), but in the case of DatePicker it doesn't show in [FormController](https://docs.angularjs.org/api/ng/type/form.FormController) object, in the example **myForm**:

		<form name="myForm"
			sf-schema="schema" sf-form="form" sf-model="model"
			ng-submit="onSubmit(myForm)" novalidate>
		</form>

**Comment by stephenbaidu** [comment]
Can you please show us your schema and form configs?

**Comment by benoror** [comment]
Sure, here is it: https://gist.github.com/benoror/213618f28cba18c19b0d#file-gistfile1-json-L47

**Comment by stephenbaidu** [comment]
Please check line 101 of both gists. There's a comma missing after `}`.

**Comment by benoror** [comment]
Oops, I actually removed some sensitive parts manually, you can assume is a valid JSON

**Comment by Dervisevic** [comment]
Check out 0.3.1 and see if it works.

**Comment by benoror** [comment]
I will ASAP, thanks!
