### ISSUE TITLE
Difficult to select Date of Birth

### ISSUE THREAD

**Issue by stephenbaidu** [Textalk/angular-schema-form-datepicker#21]
Though this add-on has an elegant ui, it is not easy to select a date of birth since you have to click several times. It will be nice to have some drill down feature for the year.

Thanks.

**Comment by Dervisevic** [comment]
This is essentially just an angular wrapper for [pick-a-date](http://amsul.ca/pickadate.js/). So all development on it is done there.

**Comment by stephenbaidu** [comment]
Okay, thanks.
