### ISSUE TITLE
Adding extra options in pickadate.js

### ISSUE THREAD

**Issue by stephenbaidu** [Textalk/angular-schema-form-datepicker#22]
How do we specify extra options available in pickadate.js. Options like selectMonths, selectYears etc.

Thanks.

**Comment by Dervisevic** [comment]
It's not in the bower version right now, it's been merged but testing didn't seem conclusive: 

https://github.com/Textalk/angular-schema-form-datepicker/pull/16

**Comment by stephenbaidu** [comment]
Okay, great.

**Comment by stephenbaidu** [comment]
The current bower version solved my issue. Thanks.
