### ISSUE TITLE
how to combine two or more html controls date , time and timezone dropdown (combiation)

### ISSUE THREAD

**Issue by kirantejj** [Textalk/angular-schema-form-datepicker#49]
example: 
Date                    Time           Timezone
10/02/2017         02:00 PM    (UTC-05:00) Eastern Time (US & Canada)

[click here for example ](http://docs.telerik.com/devtools/aspnet-ajax/controls/scheduler/accessibility-and-internationalization/images/scheduler_timezone_advancedForm.png)

i want the exact the same control in schemaform

**Comment by Dervisevic** [comment]
This addons won't do that. The timezone functionality isn't in this addon. It would have to be expanded for it or 2 separate controls, like this and a drop down, or this and a map 🗺 add on for timezones.
