### ISSUE TITLE
question: how to pass options to pickadate ? 

### ISSUE THREAD

**Issue by max-l** [Textalk/angular-schema-form-datepicker#7]
If I wanted to pass the following options : 

	$('.datepicker').pickadate({
	    labelMonthNext: 'Go to the next month',
	    labelMonthPrev: 'Go to the previous month',
	    labelMonthSelect: 'Pick a month from the dropdown',
	    labelYearSelect: 'Pick a year from the dropdown',
	    selectMonths: true,
	    selectYears: true
	})

how would I do it 

1. for a single field in a form 

2. to all date fields (default global option)

Thanks

**Comment by Dervisevic** [comment]
#16 has been merged, it will be tested and then bower released
