### ISSUE TITLE
DatePicker DEMO

### ISSUE THREAD

**Issue by Fabryprog** [Textalk/angular-schema-form-datepicker#8]
Hello,

i am searching a demo code for this module without success!!!

So i write this plunker

http://plnkr.co/edit/mjyd99

But i haven't any datepicker popup. 

Is it ok? Where am I doing wrong?

King regards

**Comment by jahnreektor** [comment]
@Fabryprog This was unbelievably helpful.  After a day+ of hitting my head on a wall, I finally understood what to do with this demo.

**Comment by Fabryprog** [comment]
:+1:
